services:
  mysql:
    image: mysql:8.0
    container_name: oliveto_mysql
    restart: unless-stopped
    network_mode: host
    environment:
      MYSQL_ROOT_PASSWORD: oliveto
      MYSQL_USER: oliveto
      MYSQL_PASSWORD: oliveto
      MYSQL_DATABASE: oliveto
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: oliveto_redis
    restart: unless-stopped
    network_mode: host
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
