-- CreateEnum
CREATE TYPE "LeadOrigin" AS ENUM ('CONTACT_FORM', 'NEWSLETTER', 'REFERRAL', 'SOCIAL_MEDIA', 'GOOGLE_ADS', 'ORGANIC_SEARCH');

-- AlterTable
ALTER TABLE "leads"
  DROP COLUMN "source",
  ADD COLUMN "origin" "LeadOrigin" NOT NULL DEFAULT 'CONTACT_FORM',
  ADD COLUMN "is_read" BOOLEAN NOT NULL DEFAULT false;
